### ISSUE TITLE
Change bars in date edit screen

### ISSUE THREAD

**Issue by songwoo** [songwoo/tracker#10]
![image](https://cloud.githubusercontent.com/assets/7820679/9152251/d7922756-3dee-11e5-802b-b3c6a9c69290.png)

Currently we are using a blue bar to signify the target date and duration. I'd like to change this to a single date entry. E.g. "In Assessment" blue bar (currently spanning 3/6 - 3/8) should just span the start day (3/6), "In data entry" should be 3/11, etc.

**Comment by Pierroutt** [comment]
Fixed

**Comment by tperin** [comment]
This issue was moved to tperin/Xogene-Tracker#10
