### ISSUE TITLE
Need DELETE button on Edit Project Branches screen

### ISSUE THREAD

**Issue by songwoo** [songwoo/tracker#11]
![image](https://cloud.githubusercontent.com/assets/7820679/9152290/72a6372c-3df0-11e5-9e80-5a1ffa2d1c80.png)

**Comment by Pierroutt** [comment]
Fixed, although some branches will still not be able to be deleted, these are the state's that are necessary for every workflow

**Comment by Pierroutt** [comment]
Also for any of the state's that don't have a red x, please do not edit the current step or next step fields.

**Comment by tperin** [comment]
This issue was moved to tperin/Xogene-Tracker#11
