### ISSUE TITLE
Edit project branches - funky!

### ISSUE THREAD

**Issue by songwoo** [songwoo/tracker#14]
![image](https://cloud.githubusercontent.com/assets/7820679/9152353/9eeb162a-3df2-11e5-8a63-8055c2927a62.png)

On "takeda - ctgov protocol" I edited the descriptive text on "Action Desc" and hit save. Nothing seemed to happen.

Then, on "takeda -eudract" I made the same edits and hit save. Then no matter what project I select from the dropdown box on top, I couldn't get any data to show up on the bottom. I then logged out and logged back in. Now the takeda-eudract list only shows the 4 states, shown.

**Comment by Pierroutt** [comment]
This might have happened because I was editing the databae, but I'm not sure. Could you try it again and see if the funky errors happen again?

**Comment by Pierroutt** [comment]
I only ask because I tried editing the action descriptions just now and it worked.

**Comment by songwoo** [comment]
I'll try again...

**Comment by songwoo** [comment]
I edited the "Action Desc" field and it did not save.

**Comment by Pierroutt** [comment]
Which step's action desc field did you edit?

**Comment by songwoo** [comment]
I changed the description on this one
![image](https://cloud.githubusercontent.com/assets/7820679/9152460/89a7bc78-3df7-11e5-8cec-983637df5ca0.png)

**Comment by Pierroutt** [comment]
If you edited the action desc of a step without a red x next to it, I think I know what the problem is, but is it important to edit the information of those actions?

**Comment by songwoo** [comment]
I see. Hold off for now. It's not important compared to the other issues.

**Comment by Pierroutt** [comment]
Ahh so it was one of those actions. I'll look into it. The other ones seem to be working

**Comment by Pierroutt** [comment]
Fixed. Although, like I said, avoid making too many changes to the actions that don't have an X next to them. And keep in mind that changing an action that has an X next to it in one project will change that action for all projects.

**Comment by tperin** [comment]
This issue was moved to tperin/Xogene-Tracker#14
