### ISSUE TITLE
Change dropdown boxes throughout the site

### ISSUE THREAD

**Issue by songwoo** [songwoo/tracker#15]
Use this
![image](https://cloud.githubusercontent.com/assets/7820679/9152382/c2516870-3df3-11e5-82ff-2a399b61f4e6.png)

Instead of this
![image](https://cloud.githubusercontent.com/assets/7820679/9152387/d7eddbf0-3df3-11e5-8aca-97b760560c74.png)

**Comment by Pierroutt** [comment]
Fixed, although I cannot seem to change the dropdown that controls the number of entries shown.

**Comment by tperin** [comment]
This issue was moved to tperin/Xogene-Tracker#15
