### ISSUE TITLE
Add comment screen

### ISSUE THREAD

**Issue by songwoo** [songwoo/tracker#16]
![image](https://cloud.githubusercontent.com/assets/7820679/9152587/a0444c48-3dfd-11e5-92cf-9b1a7ffa6f0d.png)
Remove the horizontal line behind the date field.
Make the comment field larger

**Comment by Pierroutt** [comment]
Fixed

**Comment by tperin** [comment]
This issue was moved to tperin/Xogene-Tracker#16
