### ISSUE TITLE
Move the edit comments and edit action date links

### ISSUE THREAD

**Issue by songwoo** [songwoo/tracker#17]
![image](https://cloud.githubusercontent.com/assets/7820679/9152654/3bf4e8c8-3dfe-11e5-88ee-d780155951f7.png)
Create two buttons and right justify at the same level as the "Timeline" text.

"edit dates" "edit comments"

Delete the link in
![image](https://cloud.githubusercontent.com/assets/7820679/9152660/916d9660-3dfe-11e5-9a45-b5f3da860488.png)

Delete the link in
![image](https://cloud.githubusercontent.com/assets/7820679/9152664/a4384cf4-3dfe-11e5-9844-68bf48c46cb6.png)

**Comment by Pierroutt** [comment]
Fixed

**Comment by tperin** [comment]
This issue was moved to tperin/Xogene-Tracker#17
