### ISSUE TITLE
User privilege issue

### ISSUE THREAD

**Issue by songwoo** [songwoo/tracker#18]
PM's should have the privilege to:

Edit action dates
Edit comments
Take workflow actions

Employees should only be able to Take workflow actions

**Comment by Pierroutt** [comment]
Fixed. Also, employees are only able to take actions once they are associated with a project. Although they are unable to hold or cancel a project. I can change this if you like.

**Comment by tperin** [comment]
This issue was moved to tperin/Xogene-Tracker#18
