### ISSUE TITLE
Edit comments funky

### ISSUE THREAD

**Issue by songwoo** [songwoo/tracker#19]
i edit a comment and hit save. Only seems to work for new comments. I also get this error. 
![image](https://cloud.githubusercontent.com/assets/7820679/9155371/d727dbc2-3e83-11e5-9b08-b62a061656f8.jpg)

**Comment by Pierroutt** [comment]
Fixed...Finally

**Comment by tperin** [comment]
This issue was moved to tperin/Xogene-Tracker#19
