### ISSUE TITLE
Date calculation

### ISSUE THREAD

**Issue by songwoo** [songwoo/tracker#22]
When determining the estimated date, take today's date into consideration.
The estimated "In QC" date was calculated by the system to be x days after data entry, but since this date has passed and the workflow has not progressed, the estimated date should be today's date. And all subsequent dates should be calculated based on this date as well.

![image](https://cloud.githubusercontent.com/assets/7820679/9177960/8f7f741c-3f62-11e5-95ed-1a6041f8a118.png)

**Comment by Pierroutt** [comment]
Fixed.

**Comment by tperin** [comment]
This issue was moved to tperin/Xogene-Tracker#22
