### ISSUE TITLE
Need full user management functionality

### ISSUE THREAD

**Issue by songwoo** [songwoo/tracker#23]
1. Delete user
2. Set password
3. Send welcome email to new user.

**Comment by Pierroutt** [comment]
What exactly should the welcome email say? I am assuming you want the email to show the user's username and password?

**Comment by songwoo** [comment]
It should just say

Dear FIRSTNAME

Welcome to the Xogene Study Tracker!

Please use the credentials below to login to your account.

Username: USERNAME
Temporary password: TEMPPSWD
URL: HTTPS://tracking.xogene.com

Regards,
The Tracker Team

that an account was created and

On Mon, Aug 17, 2015 at 1:37 PM, sonicfan1012 < notifications@github.com [notifications@github.com] > wrote:
What exactly should the welcome email say? I am assuming you want the email to
show the user's username and password?

—
Reply to this email directly or view it on GitHub
[https://github.com/songwoo/tracker/issues/23#issuecomment-131901225] .[https://github.com/notifications/beacon/AHdVh6B5i5FW7AgCFKZQXJbGPWKZaVlpks5oohNwgaJpZM4FpcHJ.gif]

**Comment by Pierroutt** [comment]
Functionality added. It's all on the user page.

**Comment by songwoo** [comment]
I don't see it. When I click on the user icon, I still get the error page.

_-------------------_
_Woo Song_
+1.917.410.1123
songwoo@gmail.com
http://www.linkedin.com/in/songwoo

**Comment by songwoo** [comment]
I see what you did. But the USER needs a self-service page to be able to
change her name, email and passwords.

_-------------------_
_Woo Song_
+1.917.410.1123
songwoo@gmail.com
http://www.linkedin.com/in/songwoo

**Comment by songwoo** [comment]
What is the password criteria BTW?

You should list the password criteria on the page.

**Comment by Pierroutt** [comment]
Yes, I know they need a page to be able to change all that information, that's covered under the other issue you entered. The one about the user profiles or something.
I'm going to implement that as well.

**Comment by tperin** [comment]
This issue was moved to tperin/Xogene-Tracker#23
