### ISSUE TITLE
Forgot password screen should be changed

### ISSUE THREAD

**Issue by songwoo** [songwoo/tracker#27]
It should NOT look like this. It should be a standalone page without all the other elements.

![image](https://cloud.githubusercontent.com/assets/7820679/9295574/48ea5958-4440-11e5-9bef-94fff7386e50.png)

**Comment by Pierroutt** [comment]
Fixed, looks more like the login screen now.

**Comment by songwoo** [comment]
The screen should say:

"Enter your user name or email address"

![image](https://cloud.githubusercontent.com/assets/7820679/9313864/6a65d9be-44f3-11e5-85bd-deaabf311a86.png)

Move the button below the input box.

Afterwards, the screen should say:

Instructions to reset your password has been sent to EMAILADDRESS. 

[Click here to login](https://tracker.xogene.com)

**Comment by Pierroutt** [comment]
All the aesthetic changes to the password reset screen have been made. I still don't know why it won't show anything for you, but it might work now because I reset your account.

**Comment by Pierroutt** [comment]
Oh also, the account that I made for you uses your xogene email (songw@xogene.com).

**Comment by tperin** [comment]
This issue was moved to tperin/Xogene-Tracker#27
