### ISSUE TITLE
Need new user role: "Client"

### ISSUE THREAD

**Issue by songwoo** [songwoo/tracker#28]
The role should have:
- view access to all data
- no "create study"
- no edit study
- no edit dates/comments
- no admin access

All action buttons should be grayed out except for Comment

**Comment by songwoo** [comment]
The client role might already exist but I wanted to make sure all the privileges I listed above are there.

Since I cannot neither create a password or get the system to send me one, I cannot login as a client to test this.

**Comment by Pierroutt** [comment]
Done. And you could always just create a new client account if you need to test it.

**Comment by songwoo** [comment]
Issue. Client should NOT be able to create a study. Pls fix.

_-------------------_
_Woo Song_
+1.917.410.1123
songwoo@gmail.com
http://www.linkedin.com/in/songwoo

**Comment by Pierroutt** [comment]
Fixed, shouldn't be a problem anymore.

**Comment by tperin** [comment]
This issue was moved to tperin/Xogene-Tracker#28
