### ISSUE TITLE
Need user profile page

### ISSUE THREAD

**Issue by songwoo** [songwoo/tracker#29]
Clicking on the person icon should take the user to a page where s/he can edit his name, email, password, etc.

![image](https://cloud.githubusercontent.com/assets/7820679/9295628/b9d5f694-4441-11e5-9784-ad0a9a15fdc2.png)

**Comment by Pierroutt** [comment]
Fixed.

**Comment by tperin** [comment]
This issue was moved to tperin/Xogene-Tracker#29
