### ISSUE TITLE
Entering wrong user id or email address on the login screen should raise an error

### ISSUE THREAD

**Issue by songwoo** [songwoo/tracker#34]
place the text "Incorrect user id or password - please try again" above the username text box

![image](https://cloud.githubusercontent.com/assets/7820679/9314051/80139192-44f4-11e5-857a-462739963b40.png)

**Comment by Pierroutt** [comment]
Done.

**Comment by tperin** [comment]
This issue was moved to tperin/Xogene-Tracker#34
