### ISSUE TITLE
User mgmt fields

### ISSUE THREAD

**Issue by songwoo** [songwoo/tracker#36]
Pls use proper date/time stamp for last login and acct type instead of 0, 1, etc.

![image](https://cloud.githubusercontent.com/assets/7820679/9412942/dffe1b08-47fc-11e5-96fd-80b3a6e754b9.png)

**Comment by Pierroutt** [comment]
Fixed

**Comment by tperin** [comment]
This issue was moved to tperin/Xogene-Tracker#36
