### ISSUE TITLE
The admin edit screens

### ISSUE THREAD

**Issue by songwoo** [songwoo/tracker#6]
The button to add another record should be labeled "New Record" next to "showing 1 of n entries"

![image](https://cloud.githubusercontent.com/assets/7820679/9152166/a099c9d2-3deb-11e5-98f9-f72f29668340.png)

**Comment by Pierroutt** [comment]
Fixed

**Comment by tperin** [comment]
This issue was moved to tperin/Xogene-Tracker#6
