### ISSUE TITLE
Change menu labels

### ISSUE THREAD

**Issue by songwoo** [songwoo/tracker#7]
![image](https://cloud.githubusercontent.com/assets/7820679/9152207/f1932e5e-3dec-11e5-9227-e0e43e5b8b54.png)

Change:

Edit Project Steps --> Manage Workflow States
Edit Steps in Each Project --> Manage Workflow State Order
Edit Project Branches --> Manage Workflow Steps

**Comment by Pierroutt** [comment]
Fixed

**Comment by tperin** [comment]
This issue was moved to tperin/Xogene-Tracker#7
